#!/usr/bin/env python3
"""Inject measured figures into the two shipped pages.

Both pages quote numbers that a browser cannot compute: a join across two
inspection cycles for thousands of restaurants, and the A-grade outcome test.
Those are batch jobs, so their results ship EMBEDDED in the page.

Embedded, not hand-typed. A number copied by hand into a page drifts from the
script that earned it the first time either one changes, and nothing looks
wrong when it does. This script is the only writer of those blocks, and
gates_app_test.py fails the build if a block and its JSON disagree.

    operator.html  <- reinspect_join.json   (violation persistence by code)
    check.html     <- agrade_test.json      (what follows a displayed A)

Usage:
    python3 build_pages.py            # rewrite both blocks in place
    python3 build_pages.py --check    # exit 1 if either is stale
"""
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

BEGIN = "  // ---- BEGIN GENERATED by build_pages.py - do not hand-edit ----"
END = "  // ---- END GENERATED ----"


def page(name):
    """Find a shipped page in either repo layout.

    The war room keeps scripts and pages in one folder. The public repo keeps
    evidence in analysis/ and pages in data-app/. Resolving both here is what
    lets this file stay BYTE-IDENTICAL across the two - a script that has to be
    edited per repo is a script that drifts per repo.
    """
    for c in (HERE / name, HERE.parent / "data-app" / name):
        if c.exists():
            return c
    sys.exit(f"cannot find {name} beside {Path(__file__).name} or in ../data-app/")


def ascii_json(obj):
    """Compact JSON with every non-ASCII byte escaped as \\uXXXX.

    These pages are gated pure-ASCII, so a raw multi-byte character here would
    fail the build (and render as mojibake anywhere the charset is not set).
    """
    return json.dumps(obj, ensure_ascii=True, sort_keys=True, separators=(",", ":"))


def wrap(lines):
    return "\n".join([BEGIN, *lines, END])


def operator_block(data):
    codes = {
        r["code"]: {"n": r["cited"], "rate": round(r["persist_rate"], 4),
                    "lo": round(r["lo"], 4), "hi": round(r["hi"], 4)}
        for r in data["per_code_all"]
    }
    meta = {
        "pairs": data["pairs"], "medianGapDays": data["median_gap_days"],
        "windowDays": data["window_days"], "minCited": data["min_cited"],
        "ratio": round(data["ratio"], 3),
        "facilityRate": round(data["facility"]["rate"], 4),
        "practiceRate": round(data["practice"]["rate"], 4),
    }
    return wrap([
        "  // Source: reinspect_join.json, written by reinspect_join.py.",
        f"  // {len(codes)} codes with at least {meta['minCited']} citations across "
        f"{meta['pairs']:,} paired inspections.",
        "  const PERSIST = " + ascii_json(meta) + ";",
        "  PERSIST.codes = " + ascii_json(codes) + ";",
    ])


def check_block(data):
    o = data["by_origin"]
    init, refail = o["initial"], o["reinsp_after_fail"]
    # Only the two CONFIRMED strata are exported. reinsp_unconfirmed is
    # deliberately absent: the page withholds its flag for those restaurants,
    # so shipping their rate would invite quoting a number about a population
    # the page never labels.
    meta = {
        "initialRate": round(init["fail_rate"], 4), "initialN": init["n"],
        "reinspRate": round(refail["fail_rate"], 4), "reinspN": refail["n"],
        "lookbackDays": data["lookback_days"], "failScore": data["fail_score"],
        "paired": data["paired"], "censored": data["censored"],
        "dataset": data["dataset"], "watermark": data["watermark"],
    }
    return wrap([
        "  // Source: agrade_test.json, written by agrade_test.py.",
        f"  // {refail['n']:,} A grades confirmed earned on a re-inspection that",
        f"  // answered a failed initial, vs {init['n']:,} earned on an initial.",
        "  const AGRADE = " + ascii_json(meta) + ";",
    ])


BUILDS = [
    ("operator.html", "reinspect_join.json", operator_block),
    ("check.html", "agrade_test.json", check_block),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if a page is stale instead of rewriting it")
    a = ap.parse_args()

    stale, wrote = [], []
    for page_name, src_name, builder in BUILDS:
        src = HERE / src_name
        if not src.exists():
            sys.exit(f"missing {src_name} - rerun the analysis that writes it")
        dst = page(page_name)
        text = dst.read_text()

        pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        if not pat.search(text):
            sys.exit(f"{page_name} has no generated block; expected marker:\n{BEGIN}")

        fresh = builder(json.loads(src.read_text()))
        out = pat.sub(lambda _: fresh, text, count=1)

        # Refuse BEFORE writing, not after. A check that runs post-write has
        # already shipped the thing it is refusing to ship.
        bad = sorted({"U+%04X" % ord(c) for c in out if ord(c) > 127})
        if bad:
            sys.exit(f"refusing to write {page_name}: non-ASCII "
                     f"({', '.join(bad[:6])}). Use \\uXXXX escapes.")

        if out == text:
            continue
        if a.check:
            stale.append(f"{page_name} does not match {src_name}")
            continue
        dst.write_text(out)
        wrote.append(page_name)

    if a.check:
        if stale:
            sys.exit("STALE: " + "; ".join(stale) + "\nRun: python3 build_pages.py")
        print(f"fresh: {' and '.join(p for p, _, _ in BUILDS)} match their analysis")
        return
    print(f"wrote {', '.join(wrote)}" if wrote else "unchanged: both pages already current")


if __name__ == "__main__":
    main()
