#!/usr/bin/env python3
"""Inject the measured persistence table into operator.html.

operator.html ranks a restaurant's open violations by how often that exact
violation code was still there at the re-inspection. Those rates are the output
of reinspect_join.py over ~7,000 paired inspections - a batch job, not something
a browser tab can compute. So they ship embedded in the page.

Embedded, not hand-typed. A number copied by hand into a page is a number that
drifts away from the script that earned it the first time either one changes,
and nothing fails when it does. This script is the only writer of that block,
and gates_test.py GUARD 12 fails the build if the block and the JSON disagree.

    python3 build_operator.py            # rewrite the block in place
    python3 build_operator.py --check    # exit 1 if it is stale (used by the gate)
"""
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def page(name):
    """Find a shipped page in either repo layout.

    The war room keeps the scripts and the pages in one folder. The public repo
    keeps evidence in analysis/ and pages in data-app/. Resolving both here is
    what lets this file stay BYTE-IDENTICAL across the two - a script that has
    to be edited per repo is a script that drifts per repo.
    """
    for c in (HERE / name, HERE.parent / "data-app" / name):
        if c.exists():
            return c
    sys.exit(f"cannot find {name} beside {Path(__file__).name} or in ../data-app/")


SRC = HERE / "reinspect_join.json"
PAGE = page("operator.html")

BEGIN = "  // ---- BEGIN GENERATED by build_operator.py - do not hand-edit ----"
END = "  // ---- END GENERATED ----"


def ascii_json(obj):
    """Compact JSON with every non-ASCII byte escaped.

    operator.html ships with no <meta charset> - the page wrapper owns <head> -
    so a single raw multi-byte character renders as mojibake. json.dumps with
    ensure_ascii=True emits \\uXXXX, which is exactly what the page needs.
    """
    return json.dumps(obj, ensure_ascii=True, sort_keys=True, separators=(",", ":"))


def block(data):
    codes = {
        r["code"]: {
            "n": r["cited"],
            "rate": round(r["persist_rate"], 4),
            "lo": round(r["lo"], 4),
            "hi": round(r["hi"], 4),
        }
        for r in data["per_code_all"]
    }
    meta = {
        "pairs": data["pairs"],
        "medianGapDays": data["median_gap_days"],
        "windowDays": data["window_days"],
        "minCited": data["min_cited"],
        "ratio": round(data["ratio"], 3),
        "facilityRate": round(data["facility"]["rate"], 4),
        "practiceRate": round(data["practice"]["rate"], 4),
    }
    return "\n".join([
        BEGIN,
        "  // Source: reinspect_join.json, written by reinspect_join.py.",
        f"  // {len(codes)} codes with at least {meta['minCited']} citations across "
        f"{meta['pairs']:,} paired inspections.",
        "  const PERSIST = " + ascii_json(meta) + ";",
        "  PERSIST.codes = " + ascii_json(codes) + ";",
        END,
    ])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if operator.html is stale instead of rewriting it")
    a = ap.parse_args()

    data = json.loads(SRC.read_text())
    if "per_code_all" not in data:
        sys.exit(f"{SRC.name} has no per_code_all - rerun reinspect_join.py --json")

    page = PAGE.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(page):
        sys.exit(f"{PAGE.name} has no generated block; expected marker: {BEGIN.strip()}")

    fresh = block(data)
    out = pat.sub(lambda _: fresh, page, count=1)

    if a.check:
        if out != page:
            sys.exit(f"STALE: {PAGE.name} does not match {SRC.name}. "
                     f"Run: python3 build_operator.py")
        print(f"fresh: {PAGE.name} matches {SRC.name}")
        return

    # Refuse BEFORE writing, not after. A check that runs post-write has
    # already shipped the thing it is refusing to ship.
    bad = sorted({"U+%04X" % ord(c) for c in out if ord(c) > 127})
    if bad:
        sys.exit(f"refusing to write {PAGE.name}: {len(bad)} non-ASCII code point(s) "
                 f"({', '.join(bad[:6])}). This page has no <meta charset>; use \\uXXXX.")

    if out == page:
        print(f"unchanged: {PAGE.name} already matches {SRC.name}")
        return
    PAGE.write_text(out)
    print(f"wrote {PAGE.name} ({len(data['per_code_all'])} codes)")


if __name__ == "__main__":
    main()
